export const UPDATE_INFO = "UPDATE_INFO";
export const UPDATE_WORK = "UPDATE_WORK";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";
export const UPDATE_SKILL = "UPDATE_SKILL";
export const TEMPLATE_ONE = "TEMPLATE_ONE";
export const TEMPLATE_TWO = "TEMPLATE_TWO";
export const TEMPLATE_THREE = "TEMPLATE_THREE";
export const TEMPLATE_FOUR = "TEMPLATE_FOUR";
